apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    acornsoft.io/workload-group-no: "1"
  generation: 1
  labels:
    app: commerce-inventory
  name: commerce-inventory
  namespace: bb-edu
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: commerce-inventory
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: commerce-inventory
        version: v1
    spec:
      containers:
      - image: 192.168.100.12/bb-edu/commerce-inventory:1
        imagePullPolicy: Always
        name: inventory-container
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: commerce-cocktail-t8ceb0dry5v7
